---
title: "Resultados EPF 2019"
author: "José Pernías"
date: "11/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preliminares

Bibliotecas R:
```{r}
library(tidyverse)
library(glue)
library(ggplot2)
```
Carpeta de datos:
```{r}
data_dir <- file.path("..", "data")
```

Lectura de las bases de datos:
```{r}
year <- 2019
df_names <- c("hogar", "miembros", "gastos")
file_paths <- map_chr(df_names, function(nm) {
  base <- glue("{nm}_{year}.Rdata")
  file.path(data_dir, base)
})
walk(file_paths, ~ load(.x, .GlobalEnv))
```

## Hogares 

Distribución porcentual de hogares y personas según tamaño del hogar:

 Tamaño           | Hogares | Personas 
 ---------------- |-------- | --------  
 Total	          | 100,00	| 100,00   
 1 miembro	      |  26,08	|  10,48   
 2 miembros	      |  30,32	|  24,37   
 3 miembros	      |  20,66  |	 24,91   
 4 miembros	      |  17,29	|  27,79   
 5 o más miembros |   5,64	|  12,46   

```{r}
hogar_2019 %>% count(TAMANO, wt = FACTOR) %>% mutate(pct = 100 * n / sum(n))
```

```{r}
library(srvyr)
svy_hogar_2019 <- hogar_2019 %>%
  as_survey(NUMERO, weight = FACTOR)
```

```{r}
svy_hogar_2019 %>% group_by(TAMANO) %>%
  summarise(Hogares = survey_total(), 
            Personas = survey_total(NMIEMB)) %>%
  select(-ends_with("_se")) %>%
  mutate(Hogares_pct = 100 * Hogares / sum(Hogares),
         Personas_pct = 100 * Personas / sum(Personas))

```


## Gastos

```{r}
num_households_2019 <- hogar_2019 %>% 
  summarise(n = sum(FACTOR)) %>% pull(n)

gastos_2019 %>% 
  mutate(code2 = str_sub(CODIGO, end = 2)) %>%
  group_by(code2) %>%
  summarise(total = sum(GASTO) / 1000,
            gasto_hogar = sum(GASTO) / num_households_2019)
```

## Ingresos

```{r}
hogar_2019 %>% 
  group_by(CCAA) %>%
  summarise(G = sum(GASTOT / 12), 
            h = sum(FACTOR), 
            R = sum(IMPEXAC * FACTOR),
            Gh = G / h, 
            Rh = R / h)

```

```{r}
budget <- hogar_2019 %>% 
  mutate(G = GASTOT / (FACTOR * 12), 
         R = IMPEXAC,
         D = G - R) %>%
  select(G, R, D, FACTOR)
```

```{r}
budget %>% 
  mutate(noinc = if_else(R <= 0, 1, 0)) %>%
  group_by(noinc) %>%
  count(wt = FACTOR) %>%
  ungroup() %>%
  mutate(pct = 100 * n / sum(n))
```


```{r}
budget2 <- budget %>% filter(R > 0)

ggplot(budget2) +
  geom_point(aes(x = G, y = R)) + 
  scale_x_log10() +
  scale_y_log10()
```

```{r}

eng <- lm(log(G) ~ log(R), data = budget2)
summary(eng)
```
```{r}
ggplot(budget2, aes(x = R, y = D)) +
  geom_point(alpha = 1/4, fill = "black", shape = "circle filled") 
```



```{r}
def <- lm(D ~ R, data = budget2)
summary(def)
```


## Hogares y personas por comunidad autónoma

```{r}
hogar_2019 %>% group_by(CCAA) %>% 
  count(name = "hogares", wt = FACTOR) %>%
  ungroup() %>% 
  mutate(hogares_pct = 100 * hogares / sum(hogares))
```

```{r}
hogar_2019 %>% group_by(CCAA) %>% 
  count(name = "personas", wt = FACTOR * NMIEMB) %>%
  ungroup() %>% 
  mutate(personas_pct = 100 * personas / sum(personas))
```

## Gasto por comunidad autónoma

```{r}
hogar_2019 %>% group_by(CCAA) %>% 
  summarise(Gasto = sum(GASTOT), 
            hogares = sum(FACTOR), 
            Gh = Gasto / hogares, 
            personas = sum(FACTOR * NMIEMB),
            Gp = Gasto / personas)
```
