---
title: "Lectura EPF 2020"
author: "José Pernías"
date: "20/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preliminares

Bibliotecas R:
```{r}
library(readr)
library(stringr)
library(purrr)
library(dplyr)
library(tidyr)
library(glue)
```
Carpeta de datos:
```{r}
data_dir <- file.path("..", "data")
```

Carpeta con los datos originales del INE:
```{r}
ine_data_dir <- file.path(data_dir, "INE")
```

Ediciones de la EPF que se procesan:
```{r}
years <- c(2019, 2020)
```


## Diccionario variables

```{r}
parse_vars <- function(fname, vars) {
  v <- vars %>% 
    str_trim(side = "right") %>%
    str_split("\n") %>% 
    pluck(1)
  m <- str_match(v, "^([A-Z0-9]+)[^T]+T([0-9]+),([A-Z0-9.]+)")
  tibble(file = str_to_lower(fname),
         var = m[, 2],
         start = m[, 3],
         code = m[, 4])
}

read_input_file <- function(path) {
  epf_inputs <- read_lines(path) %>%
    str_c(collapse = "\n") %>%
    str_match_all("FICHERO DE ([^*:]+)[^/]+/ ([\\s\\S]+?)EXECUTE") %>%
    pluck(1)
  
  colnames(epf_inputs) <- c("", "file", "vars")
  epf_df <- as_tibble(epf_inputs[, -1])
  
  epf_dict <- map2_dfr(epf_df$file, epf_df$vars, parse_vars) 

  width <- as.integer(str_match(epf_dict$code, "^.([0-9]+)")[, 2])
  dec <- as.integer(str_match(epf_dict$code, "\\.([0-9]+)$")[, 2])
  epf_dict %>%  mutate(width = width, 
                       dec = if_else(is.na(dec), 0L, dec),
                       type = if_else(str_starts(code, "A"), "c",
                                      if_else(dec > 0, "d", "i")))
}

build_dict <- function(year) {
  iname <- glue("Inputs SPSS {year}.txt")
  year_dir <- glue("datos_{year}")
  input_file <- file.path(ine_data_dir, year_dir, iname)
  read_input_file(input_file) 
}
```

## Lectura ficheros de datos

```{r}
read_epf_file <- function(fname, year, var_dict) {
  dict <- var_dict %>% filter(file == fname)
  year_dir <- glue("datos_{year}")
  bz_name <- glue("{fname}.bz2")
  epf_file <- file.path(ine_data_dir, year_dir, bz_name)

  df <- read_fwf(epf_file, 
                 col_positions = fwf_widths(dict$width, dict$var),
                 col_types = paste0(dict$type, collapse = ""))
  ## Adjust variables with decimals
  dec_dict <- dict %>% 
    filter(dec != 0) %>%
    select(var, dec)

  pwalk(dec_dict, function(var, dec) {
    df[, var] <<- df[, var] / 10^dec
  })

  df
}

write_data <- function(x, name, path) {
  assign(name, x)
  save(list = name, file = path, compress = "xz")
}

write_epf_data <- function(year, path) {
  epf_dict <- build_dict(year)
  
  hogar <- read_epf_file("hogar", year, epf_dict)
  db_name <- glue("hogar_{year}")
  write_data(hogar, db_name, file.path(path, glue("{db_name}.Rdata")))
  
  
  miembros <- read_epf_file("miembros", year, epf_dict)
  db_name <- glue("miembros_{year}")
  write_data(miembros, db_name, file.path(path, glue("{db_name}.Rdata")))
  
  gastos_orig <- read_epf_file("gastos", year, epf_dict)
  
  gastos_tipo <- gastos_orig %>%
    select(ANOENC, NUMERO, CODIGO, GASTMON, 
           GASTNOM1, GASTNOM2, GASTNOM3, GASTNOM4, GASTNOM5) %>%
    pivot_longer(-c(ANOENC, CODIGO, NUMERO), 
                 names_to = "TIPO",
                 values_to = "VALOR") %>%
    filter(!is.na(VALOR))
  
  gastos <- gastos_orig %>% 
    select(-(GASTNOM1:GASTNOM5))
  
  db_name <- glue("gastos_{year}")
  write_data(gastos, db_name, file.path(path, glue("{db_name}.Rdata")))
  
  db_name <- glue("gastos_tipo_{year}")
  write_data(gastos_tipo, db_name, file.path(path, glue("{db_name}.Rdata")))
}

walk(years, write_epf_data, data_dir)
```


